/**/*:
  ros__parameters:
    broker:
      host: 192.168.30.157
      port: 1883
    bridge:
      mqtt2ros:
        mqtt_topics: 
          - pingpong/ros
        pingpong/ros:
          ros_topic: pong/ros
